# syntax=docker/dockerfile:1.7

FROM golang:1.25-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/order ./services/order/cmd

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
COPY --from=build /out/order /app/order
COPY configs/order.yaml /app/configs/order.yaml
COPY configs/otel-order.yaml /app/configs/otel-order.yaml
USER nonroot:nonroot
ENTRYPOINT ["/app/order"]
