// Code generated by weaver. DO NOT EDIT.

package telemetry

// Attribute keys from the ecommerce semantic convention registry.
const (

	// Customer tier for pricing and feature gates.
	AttrEcommerceCustomerTier = "ecommerce.customer.tier"

	// Identifier of the order being processed.
	AttrEcommerceOrderId = "ecommerce.order.id"

	// Order total in the customer's billing currency.
	AttrEcommerceOrderTotal = "ecommerce.order.total"

	// Payment method selected by the customer.
	AttrEcommercePaymentMethod = "ecommerce.payment.method"

	// Category the product belongs to.
	AttrEcommerceProductCategory = "ecommerce.product.category"

	// Identifier of the product being looked up or sold.
	AttrEcommerceProductId = "ecommerce.product.id"

	// Identifier of the customer performing the operation.
	AttrEcommerceUserId = "ecommerce.user.id"
)

// Allowed values for ecommerce.customer.tier.
const (
	EcommerceCustomerTierStandard = "standard"

	EcommerceCustomerTierPremium = "premium"
)

// Allowed values for ecommerce.payment.method.
const (
	EcommercePaymentMethodCreditcard = "credit_card"

	EcommercePaymentMethodPaypal = "paypal"

	EcommercePaymentMethodApplepay = "apple_pay"
)
