// Code generated by weaver. DO NOT EDIT.

package telemetry

// Metric names and units from the ecommerce semantic convention registry.

// Number of orders currently being processed.
const (
	EcommerceOrdersActiveName = "ecommerce.orders.active"
	EcommerceOrdersActiveUnit = "{order}"
)

// End-to-end duration of processing a single order.
const (
	EcommerceOrdersProcessingDurationName = "ecommerce.orders.processing.duration"
	EcommerceOrdersProcessingDurationUnit = "s"
)

// Current value of products currently in stock, in USD.
const (
	EcommerceProductsInventoryValueName = "ecommerce.products.inventory.value"
	EcommerceProductsInventoryValueUnit = "USD"
)

// Total number of product lookups.
const (
	EcommerceProductsLookupsName = "ecommerce.products.lookups"
	EcommerceProductsLookupsUnit = "{lookup}"
)

// Total number of successful user registrations.
const (
	EcommerceUsersRegistrationsName = "ecommerce.users.registrations"
	EcommerceUsersRegistrationsUnit = "{registration}"
)
