// Code generated by weaver. DO NOT EDIT.

package telemetry

// Span names from the ecommerce semantic convention registry.
const (

	// Check that there is enough stock to fulfil a request.
	SpanEcommerceInventoryCheckName = "ecommerce.inventory.check"

	// Background processing of an order after the customer-facing request returned.
	SpanEcommerceOrderBackgroundProcessName = "ecommerce.order.background.process"

	// Look up an order by id.
	SpanEcommerceOrderGetName = "ecommerce.order.get"

	// List orders for a user.
	SpanEcommerceOrderListName = "ecommerce.order.list"

	// Process a single customer order end-to-end.
	SpanEcommerceOrderProcessName = "ecommerce.order.process"

	// Update the status of an existing order.
	SpanEcommerceOrderStatusUpdateName = "ecommerce.order.status.update"

	// Create a new product.
	SpanEcommerceProductCreateName = "ecommerce.product.create"

	// List products, optionally filtered by category.
	SpanEcommerceProductListName = "ecommerce.product.list"

	// Look up a product by id.
	SpanEcommerceProductLookupName = "ecommerce.product.lookup"

	// Update the stock count for a product.
	SpanEcommerceProductStockUpdateName = "ecommerce.product.stock.update"

	// Look up a user by id.
	SpanEcommerceUserGetName = "ecommerce.user.get"

	// List users.
	SpanEcommerceUserListName = "ecommerce.user.list"

	// Register a new user.
	SpanEcommerceUserRegisterName = "ecommerce.user.register"
)
